backend:
  name: github
  repo: marketingcar/marketingcarwebsite
  branch: main
  auth_type: implicit
  app_id: Iv23liknTwNHDWkFKz3p

publish_mode: editorial_workflow

media_folder: "public/blog/images" # Media files will be stored in the repo under public/blog/images
public_folder: "/blog/images" # The src attribute for uploaded media will begin with /blog/images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string", default: "Marketing Car" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages" # A second collection for pages
    label: "Pages" # Used in the UI
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

site_url: https://www.marketingcar.com  # Replace with your site URL
logo_url: https://www.marketingcar.com/mainlogo.png  # Replace with your logo URL

# Editor configuration
editor:
  preview: false  # Disable preview pane for now