# Add site links in DecapCMS (optional)
site_url: https://marketingcar.com
backend:
  name: git-gateway
  repo: marketingcar/marketingcarwebsite
  branch: main
  identity_url: https://auth.decapbridge.com/sites/bf3f8c30-818a-43bc-9492-d8b1e2d80471
  gateway_url: https://gateway.decapbridge.com
  auth_endpoint: /auth
  auth_scope: repo

# Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

publish_mode: editorial_workflow

media_folder: "public/blog/images" # Media files will be stored in the repo under public/blog/images
public_folder: "/blog/images" # The src attribute for uploaded media will begin with /blog/images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string", default: "Marketing Car" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages" # A second collection for pages
    label: "Pages" # Used in the UI
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

site_url: https://marketingcar.com  # Replace with your site URL
logo_url: https://www.marketingcar.com/mainlogo.png  # Replace with your logo URL

# Editor configuration
editor:
  preview: false  # Disable preview pane for now