name: Deploy "public" folder to FTP

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  web-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5  # Using a popular FTP deployment action
        with:
          server: ${{ secrets.FTP_SERVER }}  # FTP server hostname or IP address (stored in GitHub Secrets)
          username: ${{ secrets.FTP_USERNAME }}  # FTP username (stored in GitHub Secrets)
          password: ${{ secrets.FTP_PASSWORD }}  # FTP password (stored in GitHub Secrets)
          local-dir: dist/  # The local folder to deploy
          server-dir: /public_html/  # The remote folder on the FTP server
          dangerous-clean-slate: false  # Set to true to delete all files on the remote before uploading (use with caution)
